DROP TABLE IF EXISTS TELEFONO CASCADE;
DROP TABLE IF EXISTS USUARIO CASCADE;
DROP TABLE IF EXISTS USUARIOXTELEFONO CASCADE;
DROP TABLE IF EXISTS JORNADA_LABORAL CASCADE;
DROP TABLE IF EXISTS EMPLEADO CASCADE;
DROP TABLE IF EXISTS PREGRADO CASCADE;
DROP TABLE IF EXISTS POSTGRADO CASCADE;
DROP TABLE IF EXISTS ESTUDIO_SUPERIOR CASCADE;
DROP TABLE IF EXISTS HORARIO_ATENCION CASCADE;
DROP TABLE IF EXISTS ESPECIALIDAD CASCADE;
DROP TABLE IF EXISTS DOCTOR CASCADE;
DROP TABLE IF EXISTS DOCTORXHORARIO CASCADE;
DROP TABLE IF EXISTS SEDE CASCADE;
DROP TABLE IF EXISTS AREA CASCADE;
DROP TABLE IF EXISTS SEDEXAREA CASCADE;
DROP TABLE IF EXISTS PACIENTE CASCADE;
DROP TABLE IF EXISTS SERVICIO CASCADE;
DROP TABLE IF EXISTS LABORATORIO CASCADE;
DROP TABLE IF EXISTS PRUEBA_MEDICA CASCADE;
DROP TABLE IF EXISTS LABOXPRUEBA CASCADE;
DROP TABLE IF EXISTS FARMACIA CASCADE;
DROP TABLE IF EXISTS COMPONENTE CASCADE;
DROP TABLE IF EXISTS MEDICAMENTO CASCADE;
DROP TABLE IF EXISTS FARMACIAXMEDICAMENTO CASCADE;
DROP TABLE IF EXISTS CONSULTA_MEDICA CASCADE;
DROP TABLE IF EXISTS CONSULTAXPRUEBA CASCADE;
DROP TABLE IF EXISTS CONSULTAXMEDICAMENTO CASCADE;
DROP TABLE IF EXISTS HISTORIA_CLINICA CASCADE;


CREATE TABLE TELEFONO(
	NUM_TELEFONO VARCHAR(15),
	PRIMARY KEY(NUM_TELEFONO)
);

CREATE TABLE USUARIO(
	COD_USUARIO VARCHAR(12),
	NOMBRES VARCHAR(64),
	APELLIDOS VARCHAR(128),
	TIPO_DOCUMENTO VARCHAR(200),
	COD_DOCUMENTO VARCHAR(8),
	GENERO VARCHAR(20),
	FECHA_NACIMIENTO DATE,
	DIRECCION_EXACTA VARCHAR(200),
	DISTRITO VARCHAR(64),
	PROVINCIA VARCHAR(64),
	DEPARTAMENTO VARCHAR(64),
	CORREO_ELECTRONICO VARCHAR(128),
	PASSWORD VARCHAR(32),
	PRIMARY KEY(COD_USUARIO)
);

CREATE TABLE USUARIOXTELEFONO(
	COD_USUARIO VARCHAR(12),
	NUM_TELEFONO VARCHAR(9),
	FOREIGN KEY(COD_USUARIO) REFERENCES USUARIO(COD_USUARIO),
	FOREIGN KEY(NUM_TELEFONO) REFERENCES TELEFONO(NUM_TELEFONO),
	PRIMARY KEY(COD_USUARIO, NUM_TELEFONO)
);

CREATE TABLE JORNADA_LABORAL(
	NUM_TURNO VARCHAR(16),
	HORA_INICIO TIME,
	HORA_SALIDA TIME,
	PRIMARY KEY (NUM_TURNO)
);

CREATE TABLE EMPLEADO(
	COD_EMPLEADO VARCHAR(12),
	CARGO VARCHAR(64),
	NUM_TURNO VARCHAR(16),
	FOREIGN KEY(COD_EMPLEADO) REFERENCES USUARIO(COD_USUARIO),
	FOREIGN KEY(NUM_TURNO) REFERENCES JORNADA_LABORAL(NUM_TURNO),
	PRIMARY KEY(COD_EMPLEADO)
);

CREATE TABLE PREGRADO(
	ID_P VARCHAR(20),
	RUC_UNIVERSIDAD VARCHAR(50),
	NOMBRE_UNIVERSIDAD VARCHAR(200),
	ESCUELA_PROFESIONAL VARCHAR(100),
	PRIMARY KEY(ID_P)
);

CREATE TABLE POSTGRADO(
	ID_PO VARCHAR(20),
	RUC_UNIVERSIDAD VARCHAR(50),
	NOMBRE_UNIVERSIDAD VARCHAR(200),
	ESPECIALIDAD VARCHAR(100),
	PRIMARY KEY(ID_PO)
);

CREATE TABLE ESTUDIO_SUPERIOR(
	ID_ES VARCHAR(20),
	INFORMACION_MAESTRIA VARCHAR(2000),
	INFORMACION_DOCTORADO VARCHAR(2000),
	PRIMARY KEY(ID_ES)
);

CREATE TABLE HORARIO_ATENCION(
	ID_HO VARCHAR(20),
	FECHA_ATENCION DATE,
	NUM_TURNO VARCHAR(2),
	HORA_INGRESO TIME,
	HORA_SALIDA TIME,
	PRIMARY KEY(ID_HO)
);

CREATE TABLE ESPECIALIDAD(
	COD_ESPECIALIDAD VARCHAR(8),
	NOMBRE_ESPECIALIDAD VARCHAR(200),
	DURACION_ESPECIALIDAD NUMERIC(3,0),
	PRIMARY KEY(COD_ESPECIALIDAD)
);

CREATE TABLE DOCTOR(
	COD_DOCTOR VARCHAR(12) REFERENCES USUARIO,
	NUM_COLEGIO_MEDICO VARCHAR(12),
	EXPERIENCIA_PROFESIONAL VARCHAR(200),
	COD_ESPECIALIDAD_DOCTOR VARCHAR(8) REFERENCES ESPECIALIDAD,
	ID_PREGR VARCHAR(20) REFERENCES PREGRADO,
	ID_POSTG VARCHAR(20) REFERENCES POSTGRADO,
	ID_EST_SUP VARCHAR(20) REFERENCES ESTUDIO_SUPERIOR,
	PRIMARY KEY(COD_DOCTOR)
);

CREATE TABLE DOCTORXHORARIO(
	COD_DOCTOR VARCHAR(12),
	FOREIGN KEY(COD_DOCTOR) REFERENCES DOCTOR(COD_DOCTOR),
	ID_DH VARCHAR(20),
	ID_HORARIO VARCHAR(20) REFERENCES HORARIO_ATENCION,
	PRIMARY KEY(COD_DOCTOR, ID_DH)
);

CREATE TABLE SEDE(
	COD_SEDE VARCHAR(8),
	NOMBRE_SEDE VARCHAR(200),
	DIRECCION_EXACTA VARCHAR(200),
	DISTRITO VARCHAR(64),
	PROVINCIA VARCHAR(64),
	DEPARTAMENTO VARCHAR(64),
	CORREO_ELECTRONICO VARCHAR(64),
	NUM_TELEFONO_SEDE VARCHAR(9) REFERENCES TELEFONO,
	PRIMARY KEY(COD_SEDE)
);

CREATE TABLE AREA(
	COD_AREA VARCHAR(8),
	NOMBRE_AREA VARCHAR(64),
	INFORMACION VARCHAR(200),
	PRIMARY KEY(COD_AREA)
);

CREATE TABLE SEDEXAREA(
	COD_AREA VARCHAR(8),
	COD_SEDE VARCHAR(8),
	UBICACION VARCHAR(100),
	DESCRIPCION_UBICACION VARCHAR(200),
	FOREIGN KEY(COD_AREA) REFERENCES AREA(COD_AREA),
	FOREIGN KEY(COD_SEDE) REFERENCES SEDE(COD_SEDE),
	PRIMARY KEY(COD_AREA, COD_SEDE)
);

CREATE TABLE PACIENTE(
	COD_PACIENTE VARCHAR(12) REFERENCES USUARIO,
	PRIMARY KEY(COD_PACIENTE)
);

CREATE TABLE SERVICIO(
	COD_SERVICIO VARCHAR(8),
	PRIMARY KEY(COD_SERVICIO)
);

CREATE TABLE LABORATORIO(
	COD_LABORATORIO VARCHAR(8) REFERENCES SERVICIO,
	PRIMARY KEY(COD_LABORATORIO)
);

CREATE TABLE PRUEBA_MEDICA(
	COD_PRUEBA VARCHAR(8),
	NOMBRE_PRUEBA VARCHAR(100),
	TIPO_PRUEBA VARCHAR(64),
	PRIMARY KEY(COD_PRUEBA)
);

CREATE TABLE LABOXPRUEBA(
	COD_LABORATORIO VARCHAR(8),
	COD_PRUEBA VARCHAR(8),
	FOREIGN KEY(COD_LABORATORIO) REFERENCES LABORATORIO,
	FOREIGN KEY(COD_PRUEBA) REFERENCES PRUEBA_MEDICA,
	PRIMARY KEY(COD_LABORATORIO, COD_PRUEBA)
);

CREATE TABLE FARMACIA(
	COD_FARMACIA VARCHAR(8) REFERENCES SERVICIO,
	PRIMARY KEY(COD_FARMACIA)
);

CREATE TABLE COMPONENTE(
	ID_COM VARCHAR(8),
	NOMBRE_COMPONENTE VARCHAR(64),
	DESCRIPCION_COMPONENTE VARCHAR(200),
	PRIMARY KEY(ID_COM)
);

CREATE TABLE MEDICAMENTO(
	COD_MEDICAMENTO VARCHAR(8),	
	NOMBRE_MEDICAMENTO VARCHAR(64),
	PRESENTACION VARCHAR(64),
	LABORATORIO_PRODUCTOR VARCHAR(64),
	ID_COMPONENTE VARCHAR(8) REFERENCES COMPONENTE,
	PRIMARY KEY(COD_MEDICAMENTO)
);

CREATE TABLE FARMACIAXMEDICAMENTO(
	COD_FARMACIA VARCHAR(8),
	COD_MEDICAMENTO VARCHAR(8),
	FOREIGN KEY(COD_FARMACIA) REFERENCES FARMACIA(COD_FARMACIA),
	FOREIGN KEY(COD_MEDICAMENTO) REFERENCES MEDICAMENTO(COD_MEDICAMENTO),
	PRIMARY KEY(COD_FARMACIA, COD_MEDICAMENTO)
);

CREATE TABLE CONSULTA_MEDICA(
	COD_CONSULTA VARCHAR(12),
	DIAGNOSTICO VARCHAR(200),
	COD_PACIENTE VARCHAR(12),
	FECHA_PROGRAMADA_CONSULTA DATE,
	FOREIGN KEY(COD_PACIENTE) REFERENCES PACIENTE(COD_PACIENTE),
	COD_SEDE VARCHAR(8),
	FOREIGN KEY(COD_SEDE) REFERENCES SEDE(COD_SEDE),
	COD_DOCTOR VARCHAR(12),
	FOREIGN KEY(COD_DOCTOR) REFERENCES DOCTOR(COD_DOCTOR),
	PRIMARY KEY(COD_CONSULTA)
);

CREATE TABLE CONSULTAXPRUEBA(
	COD_CONSULTA VARCHAR(8),
	COD_PRUEBA VARCHAR(8),
	FECHA_PRUEBA DATE,
	HORA_INICIO_PRUEBA TIME,
	HORA_FINAL_PRUEBA TIME,
	FOREIGN KEY(COD_CONSULTA) REFERENCES CONSULTA_MEDICA(COD_CONSULTA),
	FOREIGN KEY(COD_PRUEBA) REFERENCES PRUEBA_MEDICA(COD_PRUEBA),
	PRIMARY KEY(COD_CONSULTA, COD_PRUEBA)
);

CREATE TABLE CONSULTAXMEDICAMENTO(
	COD_CONSULTA VARCHAR(8),
	COD_MEDICAMENTO VARCHAR(8),
	FECHA_COMPRA DATE,
	HORA_COMPRA TIME,
	FOREIGN KEY(COD_CONSULTA) REFERENCES CONSULTA_MEDICA(COD_CONSULTA),
	FOREIGN KEY(COD_MEDICAMENTO) REFERENCES MEDICAMENTO(COD_MEDICAMENTO),
	PRIMARY KEY(COD_CONSULTA, COD_MEDICAMENTO)
);

CREATE TABLE HISTORIA_CLINICA(
	COD_HISTORIA_CLINICA VARCHAR(12),
	COD_CONSULTA VARCHAR(8),
	FOREIGN KEY(COD_CONSULTA) REFERENCES CONSULTA_MEDICA(COD_CONSULTA),
	PRIMARY KEY(COD_HISTORIA_CLINICA)
);